# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Toan Nguyen | Homepage
email: ntoand@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Toan Nguyen homepage, portfolio, blog
keywords: Toan Dinh Nguyen, homepage, portfolio, research, blog, publication
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.toaninfo.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ntoand
github_username:  ntoand
future: true

#permalink: /blog/:categories/:year/:month/:day/:title/
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - LICENSE.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - package.json
  - script
  - spec

include:
  - _pages

google_analytics: UA-23920900-4

disqus:
  shortname: toan-nguyen-blog
